# This is a basic workflow to help you get started with Actions

name: Windows CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Installs PIP Modules
    - name: Install PIP Modules
      run: python -m pip install -r requirements.txt

    # Build Project
    - name: Build Project
      run: pyinstaller --onefile --icon="pyisotools/pyisotools.ico" "pyisotools/__main__.py" --exclude-module PySide6 --exclude-module QDarkStyle
    
    # Trusted Signing
    - name: Trusted Signing
      uses: azure/trusted-signing-action@v0.5.1
      with:
        azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
        azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        endpoint: https://eus.codesigning.azure.net/
        trusted-signing-account-name: trusted-signing
        certificate-profile-name: vscx-certificate-profile
        files-folder: dist/
        files-folder-filter: exe,dll
        
    # Upload Artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PyISOTools-win32
        path: D:\a\pyisotools-cli\pyisotools-cli\dist
